import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),
  layout("routes/admin.tsx", [
    route("dashboard", "routes/admin.dashboard.tsx"),
    route("establishments", "routes/admin.establishments._index.tsx"),
    route("establishments/new", "routes/admin.establishments.new.tsx"),
    route("establishments/:id", "routes/admin.establishments.$id.tsx"),
    route("establishments/:id/edit", "routes/admin.establishments.$id.edit.tsx"),
    route("agents", "routes/admin.agents._index.tsx"),
    route("agents/new", "routes/admin.agents.new.tsx"),
    route("agents/:id", "routes/admin.agents.$id.tsx"),
    route("agents/:id/edit", "routes/admin.agents.$id.edit.tsx"),
    route("agents/:id/devices", "routes/admin.agents.$id.devices.tsx"),
    route("devices", "routes/admin.devices._index.tsx"),
    route("devices/:id", "routes/admin.devices.$id.tsx"),
    route("beneficiaries", "routes/admin.beneficiaries.tsx"),
    route("beneficiaries/:id", "routes/admin.beneficiaries.$id.tsx"),
    route("beneficiaries/:id/activity", "routes/admin.beneficiaries.$id.activity.tsx"),
    route("beneficiaries/:id/coverage", "routes/admin.beneficiaries.$id.coverage.tsx"),
    route("beneficiaries/:id/temporary-qr", "routes/admin.beneficiaries.$id.temporary-qr.tsx"),
    route("beneficiaries/:id/costs", "routes/admin.beneficiaries.$id.costs.tsx"),
    route("enrollments", "routes/admin.enrollments.tsx"),
    route("enrollments/pending", "routes/admin.enrollments.pending.tsx"),
    route("enrollments/:id", "routes/admin.enrollments.$id.tsx"),
    route("verifications", "routes/admin.verifications.tsx"),
    route("verifications/:id", "routes/admin.verifications.$id.tsx"),
    route("temporary-qr", "routes/admin.temporary-qr.tsx"),
    route("temporary-qr/:id", "routes/admin.temporary-qr.$id.tsx"),
    route("alerts", "routes/admin.alerts.tsx"),
    route("alerts/:id", "routes/admin.alerts.$id.tsx"),
    route("fraud/rules", "routes/admin.fraud.rules.tsx"),
    route("reports", "routes/admin.reports.tsx"),
    route("reports/operations", "routes/admin.reports.operations.tsx"),
    route("reports/biometrics", "routes/admin.reports.biometrics.tsx"),
    route("reports/temporary-qr", "routes/admin.reports.temporary-qr.tsx"),
    route("reports/fraud", "routes/admin.reports.fraud.tsx"),
    route("reports/costs", "routes/admin.reports.costs.tsx"),
    route("audit", "routes/admin.audit.tsx"),
    route("audit/:id", "routes/admin.audit.$id.tsx"),
    route("settings/access", "routes/admin.settings.access.tsx"),
    route("settings/*", "routes/admin.settings.other.tsx"),
  ]),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
